# Generated by Django 5.2.11 on 2026-02-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_universitet_book_universitet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='universitet',
            name='fakultet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.fakultet'),
        ),
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
        ),
        migrations.AddField(
            model_name='universitet',
            name='fanlar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.fanlar'),
        ),
    ]
